//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

//
// This source code was auto-generated by xsd, Version=4.8.3928.0.
//
// Regenerado 2026-09-12 desde el XSD vigente del ATS del SRI
// (C:\SRI-DIMM\Documentacion\ats.xsd, el mismo que usa el DIMM oficial
// instalado en esta máquina), NO copiado del `Esquema_at.cs` del `.exe`
// `ATSfromPeach` (desactualizado: le faltaban `valorRetencionNc` y
// `regimenMicroempresa`, ambos opcionales). Ver docs/PLAN-APP3-ATS.md §1.4/§3.1.
// Comando: `xsd.exe ats.xsd /classes /namespace:PsaWeb.Ats.Esquema`.
// Es el contrato con el SRI — no se edita a mano; para actualizarlo, volver a
// generar contra el XSD vigente y revisar el diff.
//
namespace PsaWeb.Ats.Esquema {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("iva", Namespace="", IsNullable=false)]
    public partial class ivaType {
        
        private ivaTypeTipoIDInformante tipoIDInformanteField;
        
        private string idInformanteField;
        
        private string razonSocialField;
        
        private string anioField;
        
        private string mesField;
        
        private regimenSemestralType regimenMicroempresaField;
        
        private bool regimenMicroempresaFieldSpecified;
        
        private string numEstabRucField;
        
        private decimal totalVentasField;
        
        private bool totalVentasFieldSpecified;
        
        private codigoOperativoType codigoOperativoField;
        
        private detalleComprasType[] comprasField;
        
        private detalleVentasType[] ventasField;
        
        private ventaEstType[] ventasEstablecimientoField;
        
        private detalleExportacionesType[] exportacionesField;
        
        private detalleRecapType[] recapField;
        
        private detalleFideicomisosType[] fideicomisosField;
        
        private detalleAnuladosType[] anuladosField;
        
        private detalleRendFinancierosType[] rendFinancierosField;
        
        /// <remarks/>
        public ivaTypeTipoIDInformante TipoIDInformante {
            get {
                return this.tipoIDInformanteField;
            }
            set {
                this.tipoIDInformanteField = value;
            }
        }
        
        /// <remarks/>
        public string IdInformante {
            get {
                return this.idInformanteField;
            }
            set {
                this.idInformanteField = value;
            }
        }
        
        /// <remarks/>
        public string razonSocial {
            get {
                return this.razonSocialField;
            }
            set {
                this.razonSocialField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string Anio {
            get {
                return this.anioField;
            }
            set {
                this.anioField = value;
            }
        }
        
        /// <remarks/>
        public string Mes {
            get {
                return this.mesField;
            }
            set {
                this.mesField = value;
            }
        }
        
        /// <remarks/>
        public regimenSemestralType regimenMicroempresa {
            get {
                return this.regimenMicroempresaField;
            }
            set {
                this.regimenMicroempresaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool regimenMicroempresaSpecified {
            get {
                return this.regimenMicroempresaFieldSpecified;
            }
            set {
                this.regimenMicroempresaFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string numEstabRuc {
            get {
                return this.numEstabRucField;
            }
            set {
                this.numEstabRucField = value;
            }
        }
        
        /// <remarks/>
        public decimal totalVentas {
            get {
                return this.totalVentasField;
            }
            set {
                this.totalVentasField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool totalVentasSpecified {
            get {
                return this.totalVentasFieldSpecified;
            }
            set {
                this.totalVentasFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public codigoOperativoType codigoOperativo {
            get {
                return this.codigoOperativoField;
            }
            set {
                this.codigoOperativoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("detalleCompras", IsNullable=false)]
        public detalleComprasType[] compras {
            get {
                return this.comprasField;
            }
            set {
                this.comprasField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("detalleVentas", IsNullable=false)]
        public detalleVentasType[] ventas {
            get {
                return this.ventasField;
            }
            set {
                this.ventasField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("ventaEst", IsNullable=false)]
        public ventaEstType[] ventasEstablecimiento {
            get {
                return this.ventasEstablecimientoField;
            }
            set {
                this.ventasEstablecimientoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("detalleExportaciones", IsNullable=false)]
        public detalleExportacionesType[] exportaciones {
            get {
                return this.exportacionesField;
            }
            set {
                this.exportacionesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("detalleRecap", IsNullable=false)]
        public detalleRecapType[] recap {
            get {
                return this.recapField;
            }
            set {
                this.recapField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("detalleFideicomisos", IsNullable=false)]
        public detalleFideicomisosType[] fideicomisos {
            get {
                return this.fideicomisosField;
            }
            set {
                this.fideicomisosField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("detalleAnulados", IsNullable=false)]
        public detalleAnuladosType[] anulados {
            get {
                return this.anuladosField;
            }
            set {
                this.anuladosField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("detalleRendFinancieros", IsNullable=false)]
        public detalleRendFinancierosType[] rendFinancieros {
            get {
                return this.rendFinancierosField;
            }
            set {
                this.rendFinancierosField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public enum ivaTypeTipoIDInformante {
        
        /// <remarks/>
        R,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    public enum regimenSemestralType {
        
        /// <remarks/>
        SI,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    public enum codigoOperativoType {
        
        /// <remarks/>
        IVA,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class detalleComprasType {
        
        private string codSustentoField;
        
        private string tpIdProvField;
        
        private string idProvField;
        
        private string tipoComprobanteField;
        
        private string tipoProvField;
        
        private string denoProvField;
        
        private parteRelType parteRelField;
        
        private bool parteRelFieldSpecified;
        
        private string fechaRegistroField;
        
        private string establecimientoField;
        
        private string puntoEmisionField;
        
        private string secuencialField;
        
        private string fechaEmisionField;
        
        private string autorizacionField;
        
        private decimal baseNoGraIvaField;
        
        private decimal baseImponibleField;
        
        private decimal baseImpGravField;
        
        private decimal baseImpExeField;
        
        private decimal montoIceField;
        
        private decimal montoIvaField;
        
        private decimal valRetBien10Field;
        
        private bool valRetBien10FieldSpecified;
        
        private decimal valRetServ20Field;
        
        private bool valRetServ20FieldSpecified;
        
        private decimal valorRetBienesField;
        
        private decimal valRetServ50Field;
        
        private bool valRetServ50FieldSpecified;
        
        private decimal valorRetServiciosField;
        
        private decimal valRetServ100Field;
        
        private decimal valorRetencionNcField;
        
        private bool valorRetencionNcFieldSpecified;
        
        private decimal totbasesImpReembField;
        
        private bool totbasesImpReembFieldSpecified;
        
        private pagoExteriorType pagoExteriorField;
        
        private string[] formasDePagoField;
        
        private detalleAirComprasType[] airField;
        
        private string estabRetencion1Field;
        
        private string ptoEmiRetencion1Field;
        
        private string secRetencion1Field;
        
        private string autRetencion1Field;
        
        private string fechaEmiRet1Field;
        
        private string estabRetencion2Field;
        
        private string ptoEmiRetencion2Field;
        
        private string secRetencion2Field;
        
        private string autRetencion2Field;
        
        private string fechaEmiRet2Field;
        
        private string docModificadoField;
        
        private string estabModificadoField;
        
        private string ptoEmiModificadoField;
        
        private string secModificadoField;
        
        private string autModificadoField;
        
        private reembolsoType[] reembolsosField;
        
        /// <remarks/>
        public string codSustento {
            get {
                return this.codSustentoField;
            }
            set {
                this.codSustentoField = value;
            }
        }
        
        /// <remarks/>
        public string tpIdProv {
            get {
                return this.tpIdProvField;
            }
            set {
                this.tpIdProvField = value;
            }
        }
        
        /// <remarks/>
        public string idProv {
            get {
                return this.idProvField;
            }
            set {
                this.idProvField = value;
            }
        }
        
        /// <remarks/>
        public string tipoComprobante {
            get {
                return this.tipoComprobanteField;
            }
            set {
                this.tipoComprobanteField = value;
            }
        }
        
        /// <remarks/>
        public string tipoProv {
            get {
                return this.tipoProvField;
            }
            set {
                this.tipoProvField = value;
            }
        }
        
        /// <remarks/>
        public string denoProv {
            get {
                return this.denoProvField;
            }
            set {
                this.denoProvField = value;
            }
        }
        
        /// <remarks/>
        public parteRelType parteRel {
            get {
                return this.parteRelField;
            }
            set {
                this.parteRelField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool parteRelSpecified {
            get {
                return this.parteRelFieldSpecified;
            }
            set {
                this.parteRelFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string fechaRegistro {
            get {
                return this.fechaRegistroField;
            }
            set {
                this.fechaRegistroField = value;
            }
        }
        
        /// <remarks/>
        public string establecimiento {
            get {
                return this.establecimientoField;
            }
            set {
                this.establecimientoField = value;
            }
        }
        
        /// <remarks/>
        public string puntoEmision {
            get {
                return this.puntoEmisionField;
            }
            set {
                this.puntoEmisionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string secuencial {
            get {
                return this.secuencialField;
            }
            set {
                this.secuencialField = value;
            }
        }
        
        /// <remarks/>
        public string fechaEmision {
            get {
                return this.fechaEmisionField;
            }
            set {
                this.fechaEmisionField = value;
            }
        }
        
        /// <remarks/>
        public string autorizacion {
            get {
                return this.autorizacionField;
            }
            set {
                this.autorizacionField = value;
            }
        }
        
        /// <remarks/>
        public decimal baseNoGraIva {
            get {
                return this.baseNoGraIvaField;
            }
            set {
                this.baseNoGraIvaField = value;
            }
        }
        
        /// <remarks/>
        public decimal baseImponible {
            get {
                return this.baseImponibleField;
            }
            set {
                this.baseImponibleField = value;
            }
        }
        
        /// <remarks/>
        public decimal baseImpGrav {
            get {
                return this.baseImpGravField;
            }
            set {
                this.baseImpGravField = value;
            }
        }
        
        /// <remarks/>
        public decimal baseImpExe {
            get {
                return this.baseImpExeField;
            }
            set {
                this.baseImpExeField = value;
            }
        }
        
        /// <remarks/>
        public decimal montoIce {
            get {
                return this.montoIceField;
            }
            set {
                this.montoIceField = value;
            }
        }
        
        /// <remarks/>
        public decimal montoIva {
            get {
                return this.montoIvaField;
            }
            set {
                this.montoIvaField = value;
            }
        }
        
        /// <remarks/>
        public decimal valRetBien10 {
            get {
                return this.valRetBien10Field;
            }
            set {
                this.valRetBien10Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool valRetBien10Specified {
            get {
                return this.valRetBien10FieldSpecified;
            }
            set {
                this.valRetBien10FieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public decimal valRetServ20 {
            get {
                return this.valRetServ20Field;
            }
            set {
                this.valRetServ20Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool valRetServ20Specified {
            get {
                return this.valRetServ20FieldSpecified;
            }
            set {
                this.valRetServ20FieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public decimal valorRetBienes {
            get {
                return this.valorRetBienesField;
            }
            set {
                this.valorRetBienesField = value;
            }
        }
        
        /// <remarks/>
        public decimal valRetServ50 {
            get {
                return this.valRetServ50Field;
            }
            set {
                this.valRetServ50Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool valRetServ50Specified {
            get {
                return this.valRetServ50FieldSpecified;
            }
            set {
                this.valRetServ50FieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public decimal valorRetServicios {
            get {
                return this.valorRetServiciosField;
            }
            set {
                this.valorRetServiciosField = value;
            }
        }
        
        /// <remarks/>
        public decimal valRetServ100 {
            get {
                return this.valRetServ100Field;
            }
            set {
                this.valRetServ100Field = value;
            }
        }
        
        /// <remarks/>
        public decimal valorRetencionNc {
            get {
                return this.valorRetencionNcField;
            }
            set {
                this.valorRetencionNcField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool valorRetencionNcSpecified {
            get {
                return this.valorRetencionNcFieldSpecified;
            }
            set {
                this.valorRetencionNcFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public decimal totbasesImpReemb {
            get {
                return this.totbasesImpReembField;
            }
            set {
                this.totbasesImpReembField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool totbasesImpReembSpecified {
            get {
                return this.totbasesImpReembFieldSpecified;
            }
            set {
                this.totbasesImpReembFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public pagoExteriorType pagoExterior {
            get {
                return this.pagoExteriorField;
            }
            set {
                this.pagoExteriorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("formaPago", IsNullable=false)]
        public string[] formasDePago {
            get {
                return this.formasDePagoField;
            }
            set {
                this.formasDePagoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("detalleAir", IsNullable=false)]
        public detalleAirComprasType[] air {
            get {
                return this.airField;
            }
            set {
                this.airField = value;
            }
        }
        
        /// <remarks/>
        public string estabRetencion1 {
            get {
                return this.estabRetencion1Field;
            }
            set {
                this.estabRetencion1Field = value;
            }
        }
        
        /// <remarks/>
        public string ptoEmiRetencion1 {
            get {
                return this.ptoEmiRetencion1Field;
            }
            set {
                this.ptoEmiRetencion1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string secRetencion1 {
            get {
                return this.secRetencion1Field;
            }
            set {
                this.secRetencion1Field = value;
            }
        }
        
        /// <remarks/>
        public string autRetencion1 {
            get {
                return this.autRetencion1Field;
            }
            set {
                this.autRetencion1Field = value;
            }
        }
        
        /// <remarks/>
        public string fechaEmiRet1 {
            get {
                return this.fechaEmiRet1Field;
            }
            set {
                this.fechaEmiRet1Field = value;
            }
        }
        
        /// <remarks/>
        public string estabRetencion2 {
            get {
                return this.estabRetencion2Field;
            }
            set {
                this.estabRetencion2Field = value;
            }
        }
        
        /// <remarks/>
        public string ptoEmiRetencion2 {
            get {
                return this.ptoEmiRetencion2Field;
            }
            set {
                this.ptoEmiRetencion2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string secRetencion2 {
            get {
                return this.secRetencion2Field;
            }
            set {
                this.secRetencion2Field = value;
            }
        }
        
        /// <remarks/>
        public string autRetencion2 {
            get {
                return this.autRetencion2Field;
            }
            set {
                this.autRetencion2Field = value;
            }
        }
        
        /// <remarks/>
        public string fechaEmiRet2 {
            get {
                return this.fechaEmiRet2Field;
            }
            set {
                this.fechaEmiRet2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string docModificado {
            get {
                return this.docModificadoField;
            }
            set {
                this.docModificadoField = value;
            }
        }
        
        /// <remarks/>
        public string estabModificado {
            get {
                return this.estabModificadoField;
            }
            set {
                this.estabModificadoField = value;
            }
        }
        
        /// <remarks/>
        public string ptoEmiModificado {
            get {
                return this.ptoEmiModificadoField;
            }
            set {
                this.ptoEmiModificadoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string secModificado {
            get {
                return this.secModificadoField;
            }
            set {
                this.secModificadoField = value;
            }
        }
        
        /// <remarks/>
        public string autModificado {
            get {
                return this.autModificadoField;
            }
            set {
                this.autModificadoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("reembolso", IsNullable=false)]
        public reembolsoType[] reembolsos {
            get {
                return this.reembolsosField;
            }
            set {
                this.reembolsosField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    public enum parteRelType {
        
        /// <remarks/>
        SI,
        
        /// <remarks/>
        NO,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class pagoExteriorType {
        
        private pagoLocExtType pagoLocExtField;
        
        private tipoRegiType tipoRegiField;
        
        private bool tipoRegiFieldSpecified;
        
        private string paisEfecPagoGenField;
        
        private string paisEfecPagoParFisField;
        
        private string denopagoRegFisField;
        
        private string paisEfecPagoField;
        
        private aplicConvDobTribType aplicConvDobTribField;
        
        private aplicConvDobTribType pagExtSujRetNorLegField;
        
        private aplicConvDobTribType pagoRegFisField;
        
        private bool pagoRegFisFieldSpecified;
        
        /// <remarks/>
        public pagoLocExtType pagoLocExt {
            get {
                return this.pagoLocExtField;
            }
            set {
                this.pagoLocExtField = value;
            }
        }
        
        /// <remarks/>
        public tipoRegiType tipoRegi {
            get {
                return this.tipoRegiField;
            }
            set {
                this.tipoRegiField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool tipoRegiSpecified {
            get {
                return this.tipoRegiFieldSpecified;
            }
            set {
                this.tipoRegiFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string paisEfecPagoGen {
            get {
                return this.paisEfecPagoGenField;
            }
            set {
                this.paisEfecPagoGenField = value;
            }
        }
        
        /// <remarks/>
        public string paisEfecPagoParFis {
            get {
                return this.paisEfecPagoParFisField;
            }
            set {
                this.paisEfecPagoParFisField = value;
            }
        }
        
        /// <remarks/>
        public string denopagoRegFis {
            get {
                return this.denopagoRegFisField;
            }
            set {
                this.denopagoRegFisField = value;
            }
        }
        
        /// <remarks/>
        public string paisEfecPago {
            get {
                return this.paisEfecPagoField;
            }
            set {
                this.paisEfecPagoField = value;
            }
        }
        
        /// <remarks/>
        public aplicConvDobTribType aplicConvDobTrib {
            get {
                return this.aplicConvDobTribField;
            }
            set {
                this.aplicConvDobTribField = value;
            }
        }
        
        /// <remarks/>
        public aplicConvDobTribType pagExtSujRetNorLeg {
            get {
                return this.pagExtSujRetNorLegField;
            }
            set {
                this.pagExtSujRetNorLegField = value;
            }
        }
        
        /// <remarks/>
        public aplicConvDobTribType pagoRegFis {
            get {
                return this.pagoRegFisField;
            }
            set {
                this.pagoRegFisField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool pagoRegFisSpecified {
            get {
                return this.pagoRegFisFieldSpecified;
            }
            set {
                this.pagoRegFisFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    public enum pagoLocExtType {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("01")]
        Item01,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("02")]
        Item02,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    public enum tipoRegiType {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("01")]
        Item01,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("02")]
        Item02,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("03")]
        Item03,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    public enum aplicConvDobTribType {
        
        /// <remarks/>
        SI,
        
        /// <remarks/>
        NO,
        
        /// <remarks/>
        NA,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class detalleAirRenType {
        
        private string codRetAirField;
        
        private decimal depositoField;
        
        private decimal baseImpAirField;
        
        private decimal porcentajeAirField;
        
        private decimal valRetAirField;
        
        /// <remarks/>
        public string codRetAir {
            get {
                return this.codRetAirField;
            }
            set {
                this.codRetAirField = value;
            }
        }
        
        /// <remarks/>
        public decimal deposito {
            get {
                return this.depositoField;
            }
            set {
                this.depositoField = value;
            }
        }
        
        /// <remarks/>
        public decimal baseImpAir {
            get {
                return this.baseImpAirField;
            }
            set {
                this.baseImpAirField = value;
            }
        }
        
        /// <remarks/>
        public decimal porcentajeAir {
            get {
                return this.porcentajeAirField;
            }
            set {
                this.porcentajeAirField = value;
            }
        }
        
        /// <remarks/>
        public decimal valRetAir {
            get {
                return this.valRetAirField;
            }
            set {
                this.valRetAirField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class detalleRendFinancierosType {
        
        private string retenidoField;
        
        private string idRetenidoField;
        
        private aplicConvDobTribType parteRelFidField;
        
        private bool parteRelFidFieldSpecified;
        
        private string tipoReteField;
        
        private string denoBenefiField;
        
        private detalleRendFinancierosTypeAhorroPN ahorroPNField;
        
        private detalleRendFinancierosTypeCtaExenta ctaExentaField;
        
        private detalleRendFinancierosTypeDetRet[] retencionesField;
        
        /// <remarks/>
        public string retenido {
            get {
                return this.retenidoField;
            }
            set {
                this.retenidoField = value;
            }
        }
        
        /// <remarks/>
        public string idRetenido {
            get {
                return this.idRetenidoField;
            }
            set {
                this.idRetenidoField = value;
            }
        }
        
        /// <remarks/>
        public aplicConvDobTribType parteRelFid {
            get {
                return this.parteRelFidField;
            }
            set {
                this.parteRelFidField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool parteRelFidSpecified {
            get {
                return this.parteRelFidFieldSpecified;
            }
            set {
                this.parteRelFidFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string tipoRete {
            get {
                return this.tipoReteField;
            }
            set {
                this.tipoReteField = value;
            }
        }
        
        /// <remarks/>
        public string denoBenefi {
            get {
                return this.denoBenefiField;
            }
            set {
                this.denoBenefiField = value;
            }
        }
        
        /// <remarks/>
        public detalleRendFinancierosTypeAhorroPN ahorroPN {
            get {
                return this.ahorroPNField;
            }
            set {
                this.ahorroPNField = value;
            }
        }
        
        /// <remarks/>
        public detalleRendFinancierosTypeCtaExenta ctaExenta {
            get {
                return this.ctaExentaField;
            }
            set {
                this.ctaExentaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("detRet", IsNullable=false)]
        public detalleRendFinancierosTypeDetRet[] retenciones {
            get {
                return this.retencionesField;
            }
            set {
                this.retencionesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class detalleRendFinancierosTypeAhorroPN {
        
        private decimal totalDepField;
        
        private decimal rendGenField;
        
        /// <remarks/>
        public decimal totalDep {
            get {
                return this.totalDepField;
            }
            set {
                this.totalDepField = value;
            }
        }
        
        /// <remarks/>
        public decimal rendGen {
            get {
                return this.rendGenField;
            }
            set {
                this.rendGenField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class detalleRendFinancierosTypeCtaExenta {
        
        private decimal totalDepField;
        
        private decimal rendGenField;
        
        /// <remarks/>
        public decimal totalDep {
            get {
                return this.totalDepField;
            }
            set {
                this.totalDepField = value;
            }
        }
        
        /// <remarks/>
        public decimal rendGen {
            get {
                return this.rendGenField;
            }
            set {
                this.rendGenField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class detalleRendFinancierosTypeDetRet {
        
        private pagoExteriorType pagoExteriorField;
        
        private string estabRetencionField;
        
        private string ptoEmiRetencionField;
        
        private string secRetencionField;
        
        private string autRetencionField;
        
        private string fechaEmiRetField;
        
        private detalleAirRenType[] airRendField;
        
        /// <remarks/>
        public pagoExteriorType pagoExterior {
            get {
                return this.pagoExteriorField;
            }
            set {
                this.pagoExteriorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string estabRetencion {
            get {
                return this.estabRetencionField;
            }
            set {
                this.estabRetencionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string ptoEmiRetencion {
            get {
                return this.ptoEmiRetencionField;
            }
            set {
                this.ptoEmiRetencionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string secRetencion {
            get {
                return this.secRetencionField;
            }
            set {
                this.secRetencionField = value;
            }
        }
        
        /// <remarks/>
        public string autRetencion {
            get {
                return this.autRetencionField;
            }
            set {
                this.autRetencionField = value;
            }
        }
        
        /// <remarks/>
        public string fechaEmiRet {
            get {
                return this.fechaEmiRetField;
            }
            set {
                this.fechaEmiRetField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("detalleAirRen", IsNullable=false)]
        public detalleAirRenType[] airRend {
            get {
                return this.airRendField;
            }
            set {
                this.airRendField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class detalleAnuladosType {
        
        private string tipoComprobanteField;
        
        private string establecimientoField;
        
        private string puntoEmisionField;
        
        private string secuencialInicioField;
        
        private string secuencialFinField;
        
        private string autorizacionField;
        
        /// <remarks/>
        public string tipoComprobante {
            get {
                return this.tipoComprobanteField;
            }
            set {
                this.tipoComprobanteField = value;
            }
        }
        
        /// <remarks/>
        public string establecimiento {
            get {
                return this.establecimientoField;
            }
            set {
                this.establecimientoField = value;
            }
        }
        
        /// <remarks/>
        public string puntoEmision {
            get {
                return this.puntoEmisionField;
            }
            set {
                this.puntoEmisionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string secuencialInicio {
            get {
                return this.secuencialInicioField;
            }
            set {
                this.secuencialInicioField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string secuencialFin {
            get {
                return this.secuencialFinField;
            }
            set {
                this.secuencialFinField = value;
            }
        }
        
        /// <remarks/>
        public string autorizacion {
            get {
                return this.autorizacionField;
            }
            set {
                this.autorizacionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class detallefValorType {
        
        private string tipoFideicomisoField;
        
        private decimal totalFField;
        
        private decimal individualFField;
        
        private decimal porRetFField;
        
        private decimal valorRetFField;
        
        private string fechaPagoDivField;
        
        private decimal imRentaSocField;
        
        private bool imRentaSocFieldSpecified;
        
        private string anioUtDivField;
        
        private pagoExteriorType pagoExteriorField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string tipoFideicomiso {
            get {
                return this.tipoFideicomisoField;
            }
            set {
                this.tipoFideicomisoField = value;
            }
        }
        
        /// <remarks/>
        public decimal totalF {
            get {
                return this.totalFField;
            }
            set {
                this.totalFField = value;
            }
        }
        
        /// <remarks/>
        public decimal individualF {
            get {
                return this.individualFField;
            }
            set {
                this.individualFField = value;
            }
        }
        
        /// <remarks/>
        public decimal porRetF {
            get {
                return this.porRetFField;
            }
            set {
                this.porRetFField = value;
            }
        }
        
        /// <remarks/>
        public decimal valorRetF {
            get {
                return this.valorRetFField;
            }
            set {
                this.valorRetFField = value;
            }
        }
        
        /// <remarks/>
        public string fechaPagoDiv {
            get {
                return this.fechaPagoDivField;
            }
            set {
                this.fechaPagoDivField = value;
            }
        }
        
        /// <remarks/>
        public decimal imRentaSoc {
            get {
                return this.imRentaSocField;
            }
            set {
                this.imRentaSocField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool imRentaSocSpecified {
            get {
                return this.imRentaSocFieldSpecified;
            }
            set {
                this.imRentaSocFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string anioUtDiv {
            get {
                return this.anioUtDivField;
            }
            set {
                this.anioUtDivField = value;
            }
        }
        
        /// <remarks/>
        public pagoExteriorType pagoExterior {
            get {
                return this.pagoExteriorField;
            }
            set {
                this.pagoExteriorField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class detalleFideicomisosType {
        
        private string tipoBeneficiarioField;
        
        private string idBeneficiarioField;
        
        private parteRelType parteRelExpField;
        
        private bool parteRelExpFieldSpecified;
        
        private string tipoBeneficiarioCliField;
        
        private string denoBenefiField;
        
        private string rucFideicomisoField;
        
        private detallefValorType[] fValorField;
        
        /// <remarks/>
        public string tipoBeneficiario {
            get {
                return this.tipoBeneficiarioField;
            }
            set {
                this.tipoBeneficiarioField = value;
            }
        }
        
        /// <remarks/>
        public string idBeneficiario {
            get {
                return this.idBeneficiarioField;
            }
            set {
                this.idBeneficiarioField = value;
            }
        }
        
        /// <remarks/>
        public parteRelType parteRelExp {
            get {
                return this.parteRelExpField;
            }
            set {
                this.parteRelExpField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool parteRelExpSpecified {
            get {
                return this.parteRelExpFieldSpecified;
            }
            set {
                this.parteRelExpFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string tipoBeneficiarioCli {
            get {
                return this.tipoBeneficiarioCliField;
            }
            set {
                this.tipoBeneficiarioCliField = value;
            }
        }
        
        /// <remarks/>
        public string denoBenefi {
            get {
                return this.denoBenefiField;
            }
            set {
                this.denoBenefiField = value;
            }
        }
        
        /// <remarks/>
        public string rucFideicomiso {
            get {
                return this.rucFideicomisoField;
            }
            set {
                this.rucFideicomisoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("detallefValor", IsNullable=false)]
        public detallefValorType[] fValor {
            get {
                return this.fValorField;
            }
            set {
                this.fValorField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class detalleRecapType {
        
        private string establecimientoRecapField;
        
        private string identificacionRecapField;
        
        private parteRelType parteRelRecField;
        
        private bool parteRelRecFieldSpecified;
        
        private string tipoEstField;
        
        private string denoCliRecapsField;
        
        private string tipoComprobanteField;
        
        private string numeroRecapField;
        
        private string fechaPagoField;
        
        private string tarjetaCreditoField;
        
        private string fechaEmisionRecapField;
        
        private decimal consumoCeroField;
        
        private decimal consumoGravadoField;
        
        private decimal totalConsumoField;
        
        private decimal montoIvaField;
        
        private compensacionType[] compensacionesField;
        
        private decimal comisionField;
        
        private string numeroVouchersField;
        
        private decimal valRetBien10Field;
        
        private bool valRetBien10FieldSpecified;
        
        private decimal valRetServ20Field;
        
        private bool valRetServ20FieldSpecified;
        
        private decimal valorRetBienesField;
        
        private decimal valRetServ50Field;
        
        private bool valRetServ50FieldSpecified;
        
        private decimal valorRetServiciosField;
        
        private decimal valRetServ100Field;
        
        private pagoExteriorType pagoExteriorField;
        
        private detalleAirType[] airField;
        
        private string establecimientoField;
        
        private string puntoEmisionField;
        
        private string secuencialField;
        
        private string autorizacionField;
        
        private string fechaEmisionField;
        
        /// <remarks/>
        public string establecimientoRecap {
            get {
                return this.establecimientoRecapField;
            }
            set {
                this.establecimientoRecapField = value;
            }
        }
        
        /// <remarks/>
        public string identificacionRecap {
            get {
                return this.identificacionRecapField;
            }
            set {
                this.identificacionRecapField = value;
            }
        }
        
        /// <remarks/>
        public parteRelType parteRelRec {
            get {
                return this.parteRelRecField;
            }
            set {
                this.parteRelRecField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool parteRelRecSpecified {
            get {
                return this.parteRelRecFieldSpecified;
            }
            set {
                this.parteRelRecFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string tipoEst {
            get {
                return this.tipoEstField;
            }
            set {
                this.tipoEstField = value;
            }
        }
        
        /// <remarks/>
        public string denoCliRecaps {
            get {
                return this.denoCliRecapsField;
            }
            set {
                this.denoCliRecapsField = value;
            }
        }
        
        /// <remarks/>
        public string tipoComprobante {
            get {
                return this.tipoComprobanteField;
            }
            set {
                this.tipoComprobanteField = value;
            }
        }
        
        /// <remarks/>
        public string numeroRecap {
            get {
                return this.numeroRecapField;
            }
            set {
                this.numeroRecapField = value;
            }
        }
        
        /// <remarks/>
        public string fechaPago {
            get {
                return this.fechaPagoField;
            }
            set {
                this.fechaPagoField = value;
            }
        }
        
        /// <remarks/>
        public string tarjetaCredito {
            get {
                return this.tarjetaCreditoField;
            }
            set {
                this.tarjetaCreditoField = value;
            }
        }
        
        /// <remarks/>
        public string fechaEmisionRecap {
            get {
                return this.fechaEmisionRecapField;
            }
            set {
                this.fechaEmisionRecapField = value;
            }
        }
        
        /// <remarks/>
        public decimal consumoCero {
            get {
                return this.consumoCeroField;
            }
            set {
                this.consumoCeroField = value;
            }
        }
        
        /// <remarks/>
        public decimal consumoGravado {
            get {
                return this.consumoGravadoField;
            }
            set {
                this.consumoGravadoField = value;
            }
        }
        
        /// <remarks/>
        public decimal totalConsumo {
            get {
                return this.totalConsumoField;
            }
            set {
                this.totalConsumoField = value;
            }
        }
        
        /// <remarks/>
        public decimal montoIva {
            get {
                return this.montoIvaField;
            }
            set {
                this.montoIvaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("compensacion", IsNullable=false)]
        public compensacionType[] compensaciones {
            get {
                return this.compensacionesField;
            }
            set {
                this.compensacionesField = value;
            }
        }
        
        /// <remarks/>
        public decimal comision {
            get {
                return this.comisionField;
            }
            set {
                this.comisionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string numeroVouchers {
            get {
                return this.numeroVouchersField;
            }
            set {
                this.numeroVouchersField = value;
            }
        }
        
        /// <remarks/>
        public decimal valRetBien10 {
            get {
                return this.valRetBien10Field;
            }
            set {
                this.valRetBien10Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool valRetBien10Specified {
            get {
                return this.valRetBien10FieldSpecified;
            }
            set {
                this.valRetBien10FieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public decimal valRetServ20 {
            get {
                return this.valRetServ20Field;
            }
            set {
                this.valRetServ20Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool valRetServ20Specified {
            get {
                return this.valRetServ20FieldSpecified;
            }
            set {
                this.valRetServ20FieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public decimal valorRetBienes {
            get {
                return this.valorRetBienesField;
            }
            set {
                this.valorRetBienesField = value;
            }
        }
        
        /// <remarks/>
        public decimal valRetServ50 {
            get {
                return this.valRetServ50Field;
            }
            set {
                this.valRetServ50Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool valRetServ50Specified {
            get {
                return this.valRetServ50FieldSpecified;
            }
            set {
                this.valRetServ50FieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public decimal valorRetServicios {
            get {
                return this.valorRetServiciosField;
            }
            set {
                this.valorRetServiciosField = value;
            }
        }
        
        /// <remarks/>
        public decimal valRetServ100 {
            get {
                return this.valRetServ100Field;
            }
            set {
                this.valRetServ100Field = value;
            }
        }
        
        /// <remarks/>
        public pagoExteriorType pagoExterior {
            get {
                return this.pagoExteriorField;
            }
            set {
                this.pagoExteriorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("detalleAir", IsNullable=false)]
        public detalleAirType[] air {
            get {
                return this.airField;
            }
            set {
                this.airField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string establecimiento {
            get {
                return this.establecimientoField;
            }
            set {
                this.establecimientoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string puntoEmision {
            get {
                return this.puntoEmisionField;
            }
            set {
                this.puntoEmisionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string secuencial {
            get {
                return this.secuencialField;
            }
            set {
                this.secuencialField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string autorizacion {
            get {
                return this.autorizacionField;
            }
            set {
                this.autorizacionField = value;
            }
        }
        
        /// <remarks/>
        public string fechaEmision {
            get {
                return this.fechaEmisionField;
            }
            set {
                this.fechaEmisionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class compensacionType {
        
        private string tipoCompeField;
        
        private decimal montoField;
        
        /// <remarks/>
        public string tipoCompe {
            get {
                return this.tipoCompeField;
            }
            set {
                this.tipoCompeField = value;
            }
        }
        
        /// <remarks/>
        public decimal monto {
            get {
                return this.montoField;
            }
            set {
                this.montoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(detalleAirComprasType))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class detalleAirType {
        
        private string codRetAirField;
        
        private decimal baseImpAirField;
        
        private decimal porcentajeAirField;
        
        private decimal valRetAirField;
        
        /// <remarks/>
        public string codRetAir {
            get {
                return this.codRetAirField;
            }
            set {
                this.codRetAirField = value;
            }
        }
        
        /// <remarks/>
        public decimal baseImpAir {
            get {
                return this.baseImpAirField;
            }
            set {
                this.baseImpAirField = value;
            }
        }
        
        /// <remarks/>
        public decimal porcentajeAir {
            get {
                return this.porcentajeAirField;
            }
            set {
                this.porcentajeAirField = value;
            }
        }
        
        /// <remarks/>
        public decimal valRetAir {
            get {
                return this.valRetAirField;
            }
            set {
                this.valRetAirField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class detalleAirComprasType : detalleAirType {
        
        private string fechaPagoDivField;
        
        private decimal imRentaSocField;
        
        private bool imRentaSocFieldSpecified;
        
        private string anioUtDivField;
        
        private decimal numCajBanField;
        
        private bool numCajBanFieldSpecified;
        
        private decimal precCajBanField;
        
        private bool precCajBanFieldSpecified;
        
        /// <remarks/>
        public string fechaPagoDiv {
            get {
                return this.fechaPagoDivField;
            }
            set {
                this.fechaPagoDivField = value;
            }
        }
        
        /// <remarks/>
        public decimal imRentaSoc {
            get {
                return this.imRentaSocField;
            }
            set {
                this.imRentaSocField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool imRentaSocSpecified {
            get {
                return this.imRentaSocFieldSpecified;
            }
            set {
                this.imRentaSocFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string anioUtDiv {
            get {
                return this.anioUtDivField;
            }
            set {
                this.anioUtDivField = value;
            }
        }
        
        /// <remarks/>
        public decimal numCajBan {
            get {
                return this.numCajBanField;
            }
            set {
                this.numCajBanField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool numCajBanSpecified {
            get {
                return this.numCajBanFieldSpecified;
            }
            set {
                this.numCajBanFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public decimal precCajBan {
            get {
                return this.precCajBanField;
            }
            set {
                this.precCajBanField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool precCajBanSpecified {
            get {
                return this.precCajBanFieldSpecified;
            }
            set {
                this.precCajBanFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class detalleExportacionesType {
        
        private string tpIdClienteExField;
        
        private string idClienteExField;
        
        private parteRelType parteRelExpField;
        
        private bool parteRelExpFieldSpecified;
        
        private string tipoCliField;
        
        private string denoExpCliField;
        
        private tipoRegiType tipoRegiField;
        
        private bool tipoRegiFieldSpecified;
        
        private string paisEfecPagoGenField;
        
        private string paisEfecPagoParFisField;
        
        private string denopagoRegFisField;
        
        private string paisEfecExpField;
        
        private parteRelType pagoRegFisField;
        
        private bool pagoRegFisFieldSpecified;
        
        private string exportacionDeField;
        
        private string tipIngExtField;
        
        private parteRelType ingExtGravOtroPaisField;
        
        private bool ingExtGravOtroPaisFieldSpecified;
        
        private decimal impuestoOtroPaisField;
        
        private bool impuestoOtroPaisFieldSpecified;
        
        private string tipoComprobanteField;
        
        private string distAduaneroField;
        
        private string anioField;
        
        private string regimenField;
        
        private string correlativoField;
        
        private string verificadorField;
        
        private string docTranspField;
        
        private string fechaEmbarqueField;
        
        private string fueField;
        
        private decimal valorFOBField;
        
        private decimal valorFOBComprobanteField;
        
        private string establecimientoField;
        
        private string puntoEmisionField;
        
        private string secuencialField;
        
        private string autorizacionField;
        
        private string fechaEmisionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string tpIdClienteEx {
            get {
                return this.tpIdClienteExField;
            }
            set {
                this.tpIdClienteExField = value;
            }
        }
        
        /// <remarks/>
        public string idClienteEx {
            get {
                return this.idClienteExField;
            }
            set {
                this.idClienteExField = value;
            }
        }
        
        /// <remarks/>
        public parteRelType parteRelExp {
            get {
                return this.parteRelExpField;
            }
            set {
                this.parteRelExpField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool parteRelExpSpecified {
            get {
                return this.parteRelExpFieldSpecified;
            }
            set {
                this.parteRelExpFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string tipoCli {
            get {
                return this.tipoCliField;
            }
            set {
                this.tipoCliField = value;
            }
        }
        
        /// <remarks/>
        public string denoExpCli {
            get {
                return this.denoExpCliField;
            }
            set {
                this.denoExpCliField = value;
            }
        }
        
        /// <remarks/>
        public tipoRegiType tipoRegi {
            get {
                return this.tipoRegiField;
            }
            set {
                this.tipoRegiField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool tipoRegiSpecified {
            get {
                return this.tipoRegiFieldSpecified;
            }
            set {
                this.tipoRegiFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string paisEfecPagoGen {
            get {
                return this.paisEfecPagoGenField;
            }
            set {
                this.paisEfecPagoGenField = value;
            }
        }
        
        /// <remarks/>
        public string paisEfecPagoParFis {
            get {
                return this.paisEfecPagoParFisField;
            }
            set {
                this.paisEfecPagoParFisField = value;
            }
        }
        
        /// <remarks/>
        public string denopagoRegFis {
            get {
                return this.denopagoRegFisField;
            }
            set {
                this.denopagoRegFisField = value;
            }
        }
        
        /// <remarks/>
        public string paisEfecExp {
            get {
                return this.paisEfecExpField;
            }
            set {
                this.paisEfecExpField = value;
            }
        }
        
        /// <remarks/>
        public parteRelType pagoRegFis {
            get {
                return this.pagoRegFisField;
            }
            set {
                this.pagoRegFisField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool pagoRegFisSpecified {
            get {
                return this.pagoRegFisFieldSpecified;
            }
            set {
                this.pagoRegFisFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string exportacionDe {
            get {
                return this.exportacionDeField;
            }
            set {
                this.exportacionDeField = value;
            }
        }
        
        /// <remarks/>
        public string tipIngExt {
            get {
                return this.tipIngExtField;
            }
            set {
                this.tipIngExtField = value;
            }
        }
        
        /// <remarks/>
        public parteRelType ingExtGravOtroPais {
            get {
                return this.ingExtGravOtroPaisField;
            }
            set {
                this.ingExtGravOtroPaisField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ingExtGravOtroPaisSpecified {
            get {
                return this.ingExtGravOtroPaisFieldSpecified;
            }
            set {
                this.ingExtGravOtroPaisFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public decimal impuestoOtroPais {
            get {
                return this.impuestoOtroPaisField;
            }
            set {
                this.impuestoOtroPaisField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool impuestoOtroPaisSpecified {
            get {
                return this.impuestoOtroPaisFieldSpecified;
            }
            set {
                this.impuestoOtroPaisFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string tipoComprobante {
            get {
                return this.tipoComprobanteField;
            }
            set {
                this.tipoComprobanteField = value;
            }
        }
        
        /// <remarks/>
        public string distAduanero {
            get {
                return this.distAduaneroField;
            }
            set {
                this.distAduaneroField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string anio {
            get {
                return this.anioField;
            }
            set {
                this.anioField = value;
            }
        }
        
        /// <remarks/>
        public string regimen {
            get {
                return this.regimenField;
            }
            set {
                this.regimenField = value;
            }
        }
        
        /// <remarks/>
        public string correlativo {
            get {
                return this.correlativoField;
            }
            set {
                this.correlativoField = value;
            }
        }
        
        /// <remarks/>
        public string verificador {
            get {
                return this.verificadorField;
            }
            set {
                this.verificadorField = value;
            }
        }
        
        /// <remarks/>
        public string docTransp {
            get {
                return this.docTranspField;
            }
            set {
                this.docTranspField = value;
            }
        }
        
        /// <remarks/>
        public string fechaEmbarque {
            get {
                return this.fechaEmbarqueField;
            }
            set {
                this.fechaEmbarqueField = value;
            }
        }
        
        /// <remarks/>
        public string fue {
            get {
                return this.fueField;
            }
            set {
                this.fueField = value;
            }
        }
        
        /// <remarks/>
        public decimal valorFOB {
            get {
                return this.valorFOBField;
            }
            set {
                this.valorFOBField = value;
            }
        }
        
        /// <remarks/>
        public decimal valorFOBComprobante {
            get {
                return this.valorFOBComprobanteField;
            }
            set {
                this.valorFOBComprobanteField = value;
            }
        }
        
        /// <remarks/>
        public string establecimiento {
            get {
                return this.establecimientoField;
            }
            set {
                this.establecimientoField = value;
            }
        }
        
        /// <remarks/>
        public string puntoEmision {
            get {
                return this.puntoEmisionField;
            }
            set {
                this.puntoEmisionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string secuencial {
            get {
                return this.secuencialField;
            }
            set {
                this.secuencialField = value;
            }
        }
        
        /// <remarks/>
        public string autorizacion {
            get {
                return this.autorizacionField;
            }
            set {
                this.autorizacionField = value;
            }
        }
        
        /// <remarks/>
        public string fechaEmision {
            get {
                return this.fechaEmisionField;
            }
            set {
                this.fechaEmisionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ventaEstType {
        
        private string codEstabField;
        
        private decimal ventasEstabField;
        
        private decimal ivaCompField;
        
        private bool ivaCompFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string codEstab {
            get {
                return this.codEstabField;
            }
            set {
                this.codEstabField = value;
            }
        }
        
        /// <remarks/>
        public decimal ventasEstab {
            get {
                return this.ventasEstabField;
            }
            set {
                this.ventasEstabField = value;
            }
        }
        
        /// <remarks/>
        public decimal ivaComp {
            get {
                return this.ivaCompField;
            }
            set {
                this.ivaCompField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ivaCompSpecified {
            get {
                return this.ivaCompFieldSpecified;
            }
            set {
                this.ivaCompFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class detalleVentasType {
        
        private string tpIdClienteField;
        
        private string idClienteField;
        
        private parteRelType parteRelVtasField;
        
        private bool parteRelVtasFieldSpecified;
        
        private string tipoClienteField;
        
        private string denoCliField;
        
        private string tipoComprobanteField;
        
        private tipoEmisionType tipoEmisionField;
        
        private string numeroComprobantesField;
        
        private decimal baseNoGraIvaField;
        
        private decimal baseImponibleField;
        
        private decimal baseImpGravField;
        
        private decimal montoIvaField;
        
        private compensacionType[] compensacionesField;
        
        private decimal montoIceField;
        
        private bool montoIceFieldSpecified;
        
        private decimal valorRetIvaField;
        
        private decimal valorRetRentaField;
        
        private string[] formasDePagoField;
        
        /// <remarks/>
        public string tpIdCliente {
            get {
                return this.tpIdClienteField;
            }
            set {
                this.tpIdClienteField = value;
            }
        }
        
        /// <remarks/>
        public string idCliente {
            get {
                return this.idClienteField;
            }
            set {
                this.idClienteField = value;
            }
        }
        
        /// <remarks/>
        public parteRelType parteRelVtas {
            get {
                return this.parteRelVtasField;
            }
            set {
                this.parteRelVtasField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool parteRelVtasSpecified {
            get {
                return this.parteRelVtasFieldSpecified;
            }
            set {
                this.parteRelVtasFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string tipoCliente {
            get {
                return this.tipoClienteField;
            }
            set {
                this.tipoClienteField = value;
            }
        }
        
        /// <remarks/>
        public string denoCli {
            get {
                return this.denoCliField;
            }
            set {
                this.denoCliField = value;
            }
        }
        
        /// <remarks/>
        public string tipoComprobante {
            get {
                return this.tipoComprobanteField;
            }
            set {
                this.tipoComprobanteField = value;
            }
        }
        
        /// <remarks/>
        public tipoEmisionType tipoEmision {
            get {
                return this.tipoEmisionField;
            }
            set {
                this.tipoEmisionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string numeroComprobantes {
            get {
                return this.numeroComprobantesField;
            }
            set {
                this.numeroComprobantesField = value;
            }
        }
        
        /// <remarks/>
        public decimal baseNoGraIva {
            get {
                return this.baseNoGraIvaField;
            }
            set {
                this.baseNoGraIvaField = value;
            }
        }
        
        /// <remarks/>
        public decimal baseImponible {
            get {
                return this.baseImponibleField;
            }
            set {
                this.baseImponibleField = value;
            }
        }
        
        /// <remarks/>
        public decimal baseImpGrav {
            get {
                return this.baseImpGravField;
            }
            set {
                this.baseImpGravField = value;
            }
        }
        
        /// <remarks/>
        public decimal montoIva {
            get {
                return this.montoIvaField;
            }
            set {
                this.montoIvaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("compensacion", IsNullable=false)]
        public compensacionType[] compensaciones {
            get {
                return this.compensacionesField;
            }
            set {
                this.compensacionesField = value;
            }
        }
        
        /// <remarks/>
        public decimal montoIce {
            get {
                return this.montoIceField;
            }
            set {
                this.montoIceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool montoIceSpecified {
            get {
                return this.montoIceFieldSpecified;
            }
            set {
                this.montoIceFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public decimal valorRetIva {
            get {
                return this.valorRetIvaField;
            }
            set {
                this.valorRetIvaField = value;
            }
        }
        
        /// <remarks/>
        public decimal valorRetRenta {
            get {
                return this.valorRetRentaField;
            }
            set {
                this.valorRetRentaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("formaPago", IsNullable=false)]
        public string[] formasDePago {
            get {
                return this.formasDePagoField;
            }
            set {
                this.formasDePagoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    public enum tipoEmisionType {
        
        /// <remarks/>
        E,
        
        /// <remarks/>
        F,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class reembolsoType {
        
        private string tipoComprobanteReembField;
        
        private string tpIdProvReembField;
        
        private string idProvReembField;
        
        private string establecimientoReembField;
        
        private string puntoEmisionReembField;
        
        private string secuencialReembField;
        
        private string fechaEmisionReembField;
        
        private string autorizacionReembField;
        
        private decimal baseImponibleReembField;
        
        private decimal baseImpGravReembField;
        
        private decimal baseNoGraIvaReembField;
        
        private decimal baseImpExeReembField;
        
        private decimal montoIceRembField;
        
        private decimal montoIvaRembField;
        
        /// <remarks/>
        public string tipoComprobanteReemb {
            get {
                return this.tipoComprobanteReembField;
            }
            set {
                this.tipoComprobanteReembField = value;
            }
        }
        
        /// <remarks/>
        public string tpIdProvReemb {
            get {
                return this.tpIdProvReembField;
            }
            set {
                this.tpIdProvReembField = value;
            }
        }
        
        /// <remarks/>
        public string idProvReemb {
            get {
                return this.idProvReembField;
            }
            set {
                this.idProvReembField = value;
            }
        }
        
        /// <remarks/>
        public string establecimientoReemb {
            get {
                return this.establecimientoReembField;
            }
            set {
                this.establecimientoReembField = value;
            }
        }
        
        /// <remarks/>
        public string puntoEmisionReemb {
            get {
                return this.puntoEmisionReembField;
            }
            set {
                this.puntoEmisionReembField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string secuencialReemb {
            get {
                return this.secuencialReembField;
            }
            set {
                this.secuencialReembField = value;
            }
        }
        
        /// <remarks/>
        public string fechaEmisionReemb {
            get {
                return this.fechaEmisionReembField;
            }
            set {
                this.fechaEmisionReembField = value;
            }
        }
        
        /// <remarks/>
        public string autorizacionReemb {
            get {
                return this.autorizacionReembField;
            }
            set {
                this.autorizacionReembField = value;
            }
        }
        
        /// <remarks/>
        public decimal baseImponibleReemb {
            get {
                return this.baseImponibleReembField;
            }
            set {
                this.baseImponibleReembField = value;
            }
        }
        
        /// <remarks/>
        public decimal baseImpGravReemb {
            get {
                return this.baseImpGravReembField;
            }
            set {
                this.baseImpGravReembField = value;
            }
        }
        
        /// <remarks/>
        public decimal baseNoGraIvaReemb {
            get {
                return this.baseNoGraIvaReembField;
            }
            set {
                this.baseNoGraIvaReembField = value;
            }
        }
        
        /// <remarks/>
        public decimal baseImpExeReemb {
            get {
                return this.baseImpExeReembField;
            }
            set {
                this.baseImpExeReembField = value;
            }
        }
        
        /// <remarks/>
        public decimal montoIceRemb {
            get {
                return this.montoIceRembField;
            }
            set {
                this.montoIceRembField = value;
            }
        }
        
        /// <remarks/>
        public decimal montoIvaRemb {
            get {
                return this.montoIvaRembField;
            }
            set {
                this.montoIvaRembField = value;
            }
        }
    }
}
