<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\PsaWeb.Sage50\PsaWeb.Sage50.csproj" />
    <ProjectReference Include="..\PsaWeb.PeachEbills\PsaWeb.PeachEbills.csproj" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="PsaWeb.Compras.Tests" />
  </ItemGroup>

</Project>
